name: Sync atvr inventory

on:
  schedule:
    - cron: "2 12 * * 1-6"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install job deps
        run: cd jobs && npm install
      - name: Run script
        run: node ./jobs/sync-products.js