name: Sync atvr inventory

on:
  schedule:
    - cron: "0 12 * * 1-6"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script
        run: bash ./jobs/sync.sh